baseURL = 'https://samuelaudic.github.io/hugo-static/'
languageCode = "fr-fr"
title = "Mon Blog sur le Développement Web"
theme = "ananke"

[params]
description = "Un blog personnel sur le développement web, la programmation et les nouvelles technologies."
# Paramètres spécifiques au thème Ananke
showReadingTime = true