baseURL = 'https://samuelaudic.github.io/hugo-static/'
languageCode = "fr-fr"
title = "Samuel Audic, développeur web junior"
theme = "ananke"

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = false

[languages]
  [languages.en]
    title = "Samuel Audic (en)"
    weight = 1
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages
  [languages.fr]
    title = "Samuel Audic"
    weight = 2
    contentDir = "content/fr"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = "Samuel Audic"
  favicon = ""
  site_logo = ""
  description = "Samuel Audic, développeur web junior"
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-dark-blue"
  recent_posts_number = 3
  custom_css = ["theme.css"]
  body_classes = "bg-near-white"

[[params.ananke_socials]]
name = "github"
url = "https://github.com/samuelaudic/"
